"""Regulatory communications ORM model.

Append-only ledger of Bacen 24h and ANPD notifications generated by the
platform. Each row represents a single state of a single artifact
(``draft`` → ``submitted`` → ``expired``). State transitions are new
inserts, not in-place updates — same convention as ``audit_log``.

Hash chain is computed by ``app.services.regulatory_ledger`` using the
same canonical-JSON + SHA-256 algorithm as ``app.services.audit_hash``,
but per (tenant_id, kind) instead of per tenant. Bacen and ANPD have
different regulators and different audit windows; the chains stay
independent.

See ``infra/migrations/045_regulatory_communications.sql`` for the
schema and the trigger that blocks DELETE.
"""

import uuid
from datetime import UTC, datetime

from sqlalchemy import CheckConstraint, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import TIMESTAMP

from app.db.database import Base

TIMESTAMPTZ = TIMESTAMP(timezone=True)


def _utcnow() -> datetime:
    return datetime.now(UTC)


class RegulatoryCommunication(Base):
    __tablename__ = "regulatory_communications"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    case_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("aisoc_cases.id", ondelete="SET NULL"),
        nullable=True,
    )

    kind: Mapped[str] = mapped_column(String(20), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False)

    draft_md: Mapped[str] = mapped_column(Text, nullable=False)
    draft_meta: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    deadline_at: Mapped[datetime] = mapped_column(TIMESTAMPTZ, nullable=False)
    submitted_at: Mapped[datetime | None] = mapped_column(TIMESTAMPTZ, nullable=True)
    expired_at: Mapped[datetime | None] = mapped_column(TIMESTAMPTZ, nullable=True)

    approver_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    approver_email: Mapped[str | None] = mapped_column(String(255), nullable=True)
    approver_typed_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    sent_via: Mapped[str | None] = mapped_column(String(20), nullable=True)
    sent_to: Mapped[str | None] = mapped_column(String(500), nullable=True)
    dispatch_result: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    prev_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    entry_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMPTZ, nullable=False, default=_utcnow
    )
    metadata_: Mapped[dict | None] = mapped_column("metadata", JSONB, nullable=True)

    __table_args__ = (
        CheckConstraint("kind IN ('bacen', 'anpd')", name="ck_regcomm_kind"),
        CheckConstraint(
            "status IN ('draft', 'submitted', 'expired', 'cancelled')",
            name="ck_regcomm_status",
        ),
        CheckConstraint(
            "sent_via IS NULL OR sent_via IN ('email', 'webhook', 'sisbacen', 'manual')",
            name="ck_regcomm_sent_via",
        ),
    )
