#!/usr/bin/env python3
"""Run Quarry public-demo acceptance flow end to end.

Flow covered:
transaction/event -> alert ingestion -> case -> agent investigation ->
report -> audit trail -> persisted investigation ledger.

The script intentionally uses the public same-origin API by default so it
validates Nginx + Next rewrites as well as the backend services. Set
QUARRY_E2E_BASE_URL=http://127.0.0.1:8014 to test the core API directly.
"""

from __future__ import annotations

import json
import os
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from typing import Any


BASE_URL = os.getenv("QUARRY_E2E_BASE_URL", "https://quarry.12brain.org").rstrip("/")
RUN_ID = os.getenv("QUARRY_E2E_RUN_ID", f"e2e-{int(time.time())}")
TIMEOUT = float(os.getenv("QUARRY_E2E_TIMEOUT", "90"))


class StepError(RuntimeError):
    pass


def request(method: str, path: str, body: dict[str, Any] | None = None, *, expect: tuple[int, ...] = (200,)) -> Any:
    data = None
    headers = {
        "Accept": "application/json",
        "User-Agent": f"quarry-public-e2e/{RUN_ID}",
    }
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"

    req = urllib.request.Request(f"{BASE_URL}{path}", data=data, headers=headers, method=method)
    if path == "/api/v1/alerts/submit":
        req.add_header("Idempotency-Key", f"quarry.{RUN_ID}")

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            payload = resp.read()
            if resp.status not in expect:
                raise StepError(f"{method} {path} returned {resp.status}: {payload[:500]!r}")
            content_type = resp.headers.get("content-type", "")
            if "application/json" in content_type:
                return json.loads(payload.decode("utf-8"))
            return payload.decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        payload = exc.read().decode("utf-8", errors="replace")
        if exc.code in expect:
            try:
                return json.loads(payload)
            except json.JSONDecodeError:
                return payload
        raise StepError(f"{method} {path} returned {exc.code}: {payload[:1000]}") from exc


def ok(step: str, detail: str) -> None:
    print(f"[ok] {step}: {detail}", flush=True)


def poll_investigation(run_id: str) -> dict[str, Any]:
    deadline = time.time() + TIMEOUT
    last: dict[str, Any] = {}
    while time.time() < deadline:
        try:
            last = request("GET", f"/api/v1/investigations/{run_id}")
        except StepError as exc:
            # The agents service launches the background task immediately, then
            # writes the first durable ledger row asynchronously. A 404 during
            # the first seconds means "ledger row not committed yet", not a
            # permanent failure. If it is permanent, the timeout below fails
            # with the last observed state.
            if " returned 404:" not in str(exc):
                raise
            time.sleep(1)
            continue
        status = last.get("status")
        if status == "completed":
            return last
        if status == "failed":
            raise StepError(f"investigation failed: {last}")
        time.sleep(2)
    raise StepError(f"investigation did not complete within {TIMEOUT}s; last={last}")


def main() -> None:
    now = datetime.now(timezone.utc).isoformat()

    health = request("GET", "/api/health")
    ok("health", health.get("status", "unknown"))

    alert = request(
        "POST",
        "/api/v1/alerts/submit",
        {
            "connector_id": "e2e-financial-core",
            "connector_type": "financial-core",
            "source_format": "ocsf",
            "title": f"E2E financial transaction anomaly {RUN_ID}",
            "description": (
                "High-value outbound transfer from a financial operator outside the "
                "approved change window; generated by the public acceptance flow."
            ),
            "severity": "critical",
            "tags": ["e2e", RUN_ID, "financial-control"],
            "events": [
                {
                    "class_name": "financial_transaction",
                    "activity_name": "Outbound PIX/TED transfer approval",
                    "severity": "critical",
                    "category_name": "fraud_risk",
                    "published": now,
                    "amount": 987000.25,
                    "currency": "BRL",
                    "transaction_id": RUN_ID,
                    "user": {"email": "tesouraria.demo@quarry.local", "name": "Demo Treasury Operator"},
                    "src_endpoint": {"hostname": "core-banking-app-07", "ip": "10.20.7.18"},
                    "dst_endpoint": {"ip": "198.51.100.42", "hostname": "external-beneficiary-risk"},
                    "message": "High-value transaction approved after device-risk score spike.",
                    "risk_score": 98,
                }
            ],
        },
        expect=(200, 201),
    )
    alert_id = alert["id"]
    ok("event -> alert", f"alert_id={alert_id} severity={alert['severity']}")

    explanation = request("POST", f"/api/v1/alerts/{alert_id}/explain")
    ok("alert -> explanation", f"llm_used={explanation.get('llm_used')} actions={len(explanation.get('suggested_actions', []))}")

    case = request(
        "POST",
        "/api/v1/cases",
        {
            "title": f"E2E financial containment case {RUN_ID}",
            "description": "Acceptance case created from a real submitted transaction event.",
            "severity": "critical",
            "assignee": "demo@quarry.dev",
            "alert_ids": [alert_id],
            "mitre_techniques": ["T1078", "T1566"],
            "compliance_frameworks": ["BACEN", "SOC2"],
            "tags": {"e2e_run": RUN_ID, "domain": "financial_controls"},
        },
        expect=(201,),
    )
    case_id = case["id"]
    ok("alert -> case", f"case_id={case_id} alert_count={len(case.get('alert_ids', []))}")

    note = request(
        "POST",
        f"/api/v1/cases/{case_id}/comments",
        {"body": f"E2E acceptance note for run {RUN_ID}: transaction, alert, case and agent path validated.", "is_system": True},
        expect=(201,),
    )
    ok("case timeline", f"comment_id={note['id']}")

    launched = request(
        "POST",
        f"/api/v1/cases/{case_id}/investigate",
        {"alert_summary": f"{alert['title']} | amount=987000.25 BRL | risk_score=98"},
    )
    inv_run_id = launched["run_id"]
    ok("case -> agent", f"run_id={inv_run_id} status={launched['status']}")

    investigation = poll_investigation(inv_run_id)
    ok("agent completed", f"events={investigation.get('event_count', 0)}")

    closed = request(
        "POST",
        f"/api/v1/investigations/{inv_run_id}/close",
        {"analyst_note": f"Public E2E acceptance run {RUN_ID}; generated after the agent completed."},
    )
    if not closed.get("artifact_id"):
        raise StepError(f"investigation close did not return an artifact: {closed}")
    ok("agent -> report", f"artifact_id={closed['artifact_id']}")

    report_pdf = request("GET", f"/api/v1/investigations/{inv_run_id}/summary.pdf")
    if len(report_pdf.encode("utf-8")) < 500:
        raise StepError("investigation summary PDF response was unexpectedly small")
    ok("report download", f"bytes={len(report_pdf.encode('utf-8'))}")

    summary_html = request("GET", f"/api/v1/cases/{case_id}/summary?format=html")
    ok("case -> summary", f"html_bytes={len(summary_html.encode('utf-8'))}")

    audit = request("GET", "/api/v1/audit?page_size=25&action=alerts.explain&resource=alert")
    matching_audit = [item for item in audit.get("items", []) if item.get("resource_id") == alert_id]
    if not matching_audit:
        raise StepError(f"expected audit event for alert explain, got {audit}")
    ok("audit trail", f"rows={audit['total']} matched={matching_audit[0]['id']}")

    ledger = request("GET", f"/api/v1/investigations/{inv_run_id}/events")
    event_count = len(ledger.get("items", []))
    if event_count < 1:
        raise StepError(f"expected persisted investigation ledger events, got {ledger}")
    ok("investigation ledger", f"events={event_count}")

    print(
        json.dumps(
            {
                "run": RUN_ID,
                "base_url": BASE_URL,
                "alert_id": alert_id,
                "case_id": case_id,
                "investigation_run_id": inv_run_id,
                "audit_rows": audit["total"],
                "ledger_events": event_count,
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
